repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3
        args: [--target-version=py39]
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          [
            flake8-bandit==2.1.2,
            flake8-bugbear==22.1.11,
            flake8-datetimez==20.10.0,
            flake8-debugger==4.0.0,
            flake8-print==4.0.0,
            flake8-return==1.1.3,
          ]
