repos:
  - repo: https://github.com/ambv/black
    rev: "23.1.0"
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [
            flake8-bandit==4.1.1,
            # No need for flake8-black
            flake8-bugbear==23.6.5,
            flake8-datetimez==20.10.0,
            flake8-debugger==4.1.2,
            # No need for flake8-isort
            flake8-print==5.0.0,
            flake8-return==1.1.3,
          ]
