name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Test with black
        run: |
          black . --check --target-version py37

      - name: Test with flake8
        run: |
          flake8 .

      # Currently the version of apsw specified in requirements.txt file is quite old
      # https://github.com/rogerbinns/apsw/issues/310
      - name: Fix dependencies
        run: |
          pip install "apsw==3.36.0.post1"
          
      - name: Set up mypy cache
        uses: actions/cache@v3.0.3
        with:
          path: .mypy_cache
          key: mypy1-${{ hashFiles('./graphqldb/**/*.py') }}-${{ hashFiles('./tests/**/*.py') }}
          restore-keys: mypy1-

      - name: Test with mypy
        run: |
          mypy .          

      - name: Install self
        run: |
          pip install --no-cache-dir --no-dependencies -e .

      - name: Test with pytest
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
